### ISSUE TITLE
version llvm dependency: AttributeError: 'module' object has no attribute 'TargetMachine'  with 0.6+svn105-2

### ISSUE THREAD

**Issue by yarikoptic** [ContinuumIO/llvmmath#2]
```
$> python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import llvmmath
  File "/home/yoh/deb/perspect/llvmmath/llvmmath/__init__.py", line 18, in <module>
    from .libs import get_default_math_lib, get_mathlib_so, get_llvm_mathlib
  File "/home/yoh/deb/perspect/llvmmath/llvmmath/libs.py", line 15, in <module>
    from . import build, ltypes, naming, llvm_support, callconv
  File "/home/yoh/deb/perspect/llvmmath/llvmmath/ltypes.py", line 74, in <module>
    l_longdouble = get_longdouble_type()
  File "/home/yoh/deb/perspect/llvmmath/llvmmath/ltypes.py", line 63, in get_longdouble_type
    return guess_longdouble_type()
  File "/home/yoh/deb/perspect/llvmmath/llvmmath/ltypes.py", line 22, in guess_longdouble_type
    is_ppc, is_x86 = get_target_triple()
  File "/home/yoh/deb/perspect/llvmmath/llvmmath/ltypes.py", line 47, in get_target_triple
    target_machine = llvm.ee.TargetMachine.new()
AttributeError: 'module' object has no attribute 'TargetMachine'
...
(Pdb) dir(llvm.ee)
['BO_BIG_ENDIAN', 'BO_LITTLE_ENDIAN', 'ExecutionEngine', 'GenericValue', 'TargetData', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_core', '_unpack_generic_values', '_util', 'check_is_generic_value', 'core', 'llvm']

```

on a Debian system in a virtualenv, python 2.7, python-llvm  0.6+svn105-2.  Ok with 0.11.3-1

**Comment by yuvallanger** [comment]
I was trying to install numba using:

```
$ pip install --user numba
```

~/.pip/pip.log:

```
------------------------------------------------------------
/usr/bin/pip run on Sat Oct  5 14:20:09 2013
Downloading/unpacking numba

  Running setup.py egg_info for package numba

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/tmp/pip-build-yankel/numba/setup.py", line 56, in <module>

        import llvmmath

    ImportError: No module named llvmmath

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-yankel/numba/setup.py", line 56, in <module>

    import llvmmath

ImportError: No module named llvmmath

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-yankel/numba

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-yankel/numba
```

So I did:

```
$ pip install --user llvmmath
```

~/.pip/pip.log

```
------------------------------------------------------------
/usr/bin/pip run on Sat Oct  5 14:31:20 2013
Downloading/unpacking llvmmath

  Running setup.py egg_info for package llvmmath

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/tmp/pip-build-yankel/llvmmath/setup.py", line 13, in <module>

        import llvmmath

      File "llvmmath/__init__.py", line 17, in <module>

        from .libs import get_default_math_lib, get_mathlib_so, get_llvm_mathlib

      File "llvmmath/libs.py", line 15, in <module>

        from . import build, ltypes, naming, llvm_support, callconv

      File "llvmmath/ltypes.py", line 74, in <module>

        l_longdouble = get_longdouble_type()

      File "llvmmath/ltypes.py", line 63, in get_longdouble_type

        return guess_longdouble_type()

      File "llvmmath/ltypes.py", line 22, in guess_longdouble_type

        is_ppc, is_x86 = get_target_triple()

      File "llvmmath/ltypes.py", line 47, in get_target_triple

        target_machine = llvm.ee.TargetMachine.new()

    AttributeError: 'module' object has no attribute 'TargetMachine'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-yankel/llvmmath/setup.py", line 13, in <module>

    import llvmmath

  File "llvmmath/__init__.py", line 17, in <module>

    from .libs import get_default_math_lib, get_mathlib_so, get_llvm_mathlib

  File "llvmmath/libs.py", line 15, in <module>

    from . import build, ltypes, naming, llvm_support, callconv

  File "llvmmath/ltypes.py", line 74, in <module>

    l_longdouble = get_longdouble_type()

  File "llvmmath/ltypes.py", line 63, in get_longdouble_type

    return guess_longdouble_type()

  File "llvmmath/ltypes.py", line 22, in guess_longdouble_type

    is_ppc, is_x86 = get_target_triple()

  File "llvmmath/ltypes.py", line 47, in get_target_triple

    target_machine = llvm.ee.TargetMachine.new()

AttributeError: 'module' object has no attribute 'TargetMachine'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-yankel/llvmmath

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-yankel/llvmmath
```

**Comment by florian-wagner** [comment]
+1 I have the same error.

**Comment by dabliss** [comment]
+1 Same here.

**Comment by eprparadox** [comment]
+1 same

**Comment by Slater-Victoroff** [comment]
+1 Also have the same error.

**Comment by valhallasw** [comment]
The following worked for me on Ubuntu 12.04 LTS:

``` lang=bash
sudo aptitude install llvm-3.1-dev
LLVM_CONFIG_PATH=`which llvm-config-3.1` pip install llvmpy==0.10.0
pip install llvmmath
pip install --upgrade setuptools distribute
pip install numba
```

...except I now end up with

```
>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/__init__.py", line 82, in <module>
    from numba.decorators import *
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/decorators.py", line 25, in <module>
    environment.NumbaEnvironment.get_environment().link_cbuilder_utilities()
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/environment.py", line 883, in link_cbuilder_utilities
    self.context.cbuilder_library.declare_registered(self)
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/utility/cbuilder/library.py", line 39, in declare_registered
    self.declare(registered_utility, env, self.module)
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/utility/cbuilder/library.py", line 43, in declare
    specialized_cdef, lfunc = declare(numba_cdef, env, self.module)
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/utility/cbuilder/library.py", line 11, in declare
    lfunc = specialized_cdef.define(global_module) #, optimize=False)
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/llvm_cbuilder/builder.py", line 814, in define
    self.body(*self.cbuilder.args)
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/utility/cbuilder/refcounting.py", line 92, in body
    with self.ifelse(not_null(obj)) as ifelse:
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/numba/utility/cbuilder/refcounting.py", line 35, in not_null
    return ptr.cast(shortnames.py_ssize_t) != const(ptr, 0)
  File "/home/valhallasw/venv/local/lib/python2.7/site-packages/llvm_cbuilder/builder.py", line 1156, in cast
    raise CastError(self.type, ty)
llvm_cbuilder.builder.CastError: Cannot cast from { i64, i8* }* to i64
```

when I try to import numba.

Finally, I installed anaconda, which fortunately _did_ work.
